package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Actor generated by hbm2java
 */
public class Actor  implements java.io.Serializable {


     private int identificacion;
     private String nombActor;
     private Date fechaNacimiento;
     private Set actorPeliculas = new HashSet(0);

    public Actor() {
    }

	
    public Actor(int identificacion, String nombActor, Date fechaNacimiento) {
        this.identificacion = identificacion;
        this.nombActor = nombActor;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Actor(int identificacion, String nombActor, Date fechaNacimiento, Set actorPeliculas) {
       this.identificacion = identificacion;
       this.nombActor = nombActor;
       this.fechaNacimiento = fechaNacimiento;
       this.actorPeliculas = actorPeliculas;
    }
   
    public int getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(int identificacion) {
        this.identificacion = identificacion;
    }
    public String getNombActor() {
        return this.nombActor;
    }
    
    public void setNombActor(String nombActor) {
        this.nombActor = nombActor;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getActorPeliculas() {
        return this.actorPeliculas;
    }
    
    public void setActorPeliculas(Set actorPeliculas) {
        this.actorPeliculas = actorPeliculas;
    }




}


