package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1



/**
 * DirectorPelicula generated by hbm2java
 */
public class DirectorPelicula  implements java.io.Serializable {


     private Integer iddirectorPelicula;
     private Director director;
     private Pelicula pelicula;

    public DirectorPelicula() {
    }

    public DirectorPelicula(Director director, Pelicula pelicula) {
       this.director = director;
       this.pelicula = pelicula;
    }
   
    public Integer getIddirectorPelicula() {
        return this.iddirectorPelicula;
    }
    
    public void setIddirectorPelicula(Integer iddirectorPelicula) {
        this.iddirectorPelicula = iddirectorPelicula;
    }
    public Director getDirector() {
        return this.director;
    }
    
    public void setDirector(Director director) {
        this.director = director;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }




}


