package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String nombGener;
     private Set peliculas = new HashSet(0);

    public Genero() {
    }

	
    public Genero(String nombGener) {
        this.nombGener = nombGener;
    }
    public Genero(String nombGener, Set peliculas) {
       this.nombGener = nombGener;
       this.peliculas = peliculas;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombGener() {
        return this.nombGener;
    }
    
    public void setNombGener(String nombGener) {
        this.nombGener = nombGener;
    }
    public Set getPeliculas() {
        return this.peliculas;
    }
    
    public void setPeliculas(Set peliculas) {
        this.peliculas = peliculas;
    }




}


