package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Idioma generated by hbm2java
 */
public class Idioma  implements java.io.Serializable {


     private Integer ididioma;
     private String nombIdioma;
     private Set peliculaIdiomas = new HashSet(0);

    public Idioma() {
    }

	
    public Idioma(String nombIdioma) {
        this.nombIdioma = nombIdioma;
    }
    public Idioma(String nombIdioma, Set peliculaIdiomas) {
       this.nombIdioma = nombIdioma;
       this.peliculaIdiomas = peliculaIdiomas;
    }
   
    public Integer getIdidioma() {
        return this.ididioma;
    }
    
    public void setIdidioma(Integer ididioma) {
        this.ididioma = ididioma;
    }
    public String getNombIdioma() {
        return this.nombIdioma;
    }
    
    public void setNombIdioma(String nombIdioma) {
        this.nombIdioma = nombIdioma;
    }
    public Set getPeliculaIdiomas() {
        return this.peliculaIdiomas;
    }
    
    public void setPeliculaIdiomas(Set peliculaIdiomas) {
        this.peliculaIdiomas = peliculaIdiomas;
    }




}


