package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModoPago generated by hbm2java
 */
public class ModoPago  implements java.io.Serializable {


     private Integer idModoPago;
     private String nombre;
     private String detalles;
     private Set facturas = new HashSet(0);

    public ModoPago() {
    }

	
    public ModoPago(String nombre, String detalles) {
        this.nombre = nombre;
        this.detalles = detalles;
    }
    public ModoPago(String nombre, String detalles, Set facturas) {
       this.nombre = nombre;
       this.detalles = detalles;
       this.facturas = facturas;
    }
   
    public Integer getIdModoPago() {
        return this.idModoPago;
    }
    
    public void setIdModoPago(Integer idModoPago) {
        this.idModoPago = idModoPago;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(String detalles) {
        this.detalles = detalles;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }




}


