package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private int isan;
     private Clasificacion clasificacion;
     private Genero genero;
     private Instancia instancia;
     private String titulo;
     private Date anoProdu;
     private String duracion;
     private byte precio;
     private String calificacion;
     private byte[] ruta;
     private Set actorPeliculas = new HashSet(0);
     private Set directorPeliculas = new HashSet(0);
     private Set detalles = new HashSet(0);
     private Set productorPeliculas = new HashSet(0);
     private Set peliculaIdiomas = new HashSet(0);

    public Pelicula() {
    }

	
    public Pelicula(int isan, Clasificacion clasificacion, Genero genero, Instancia instancia, String titulo, Date anoProdu, String duracion, byte precio, String calificacion, byte[] ruta) {
        this.isan = isan;
        this.clasificacion = clasificacion;
        this.genero = genero;
        this.instancia = instancia;
        this.titulo = titulo;
        this.anoProdu = anoProdu;
        this.duracion = duracion;
        this.precio = precio;
        this.calificacion = calificacion;
        this.ruta = ruta;
    }
    public Pelicula(int isan, Clasificacion clasificacion, Genero genero, Instancia instancia, String titulo, Date anoProdu, String duracion, byte precio, String calificacion, byte[] ruta, Set actorPeliculas, Set directorPeliculas, Set detalles, Set productorPeliculas, Set peliculaIdiomas) {
       this.isan = isan;
       this.clasificacion = clasificacion;
       this.genero = genero;
       this.instancia = instancia;
       this.titulo = titulo;
       this.anoProdu = anoProdu;
       this.duracion = duracion;
       this.precio = precio;
       this.calificacion = calificacion;
       this.ruta = ruta;
       this.actorPeliculas = actorPeliculas;
       this.directorPeliculas = directorPeliculas;
       this.detalles = detalles;
       this.productorPeliculas = productorPeliculas;
       this.peliculaIdiomas = peliculaIdiomas;
    }
   
    public int getIsan() {
        return this.isan;
    }
    
    public void setIsan(int isan) {
        this.isan = isan;
    }
    public Clasificacion getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(Clasificacion clasificacion) {
        this.clasificacion = clasificacion;
    }
    public Genero getGenero() {
        return this.genero;
    }
    
    public void setGenero(Genero genero) {
        this.genero = genero;
    }
    public Instancia getInstancia() {
        return this.instancia;
    }
    
    public void setInstancia(Instancia instancia) {
        this.instancia = instancia;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getAnoProdu() {
        return this.anoProdu;
    }
    
    public void setAnoProdu(Date anoProdu) {
        this.anoProdu = anoProdu;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public byte getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(byte precio) {
        this.precio = precio;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public byte[] getRuta() {
        return this.ruta;
    }
    
    public void setRuta(byte[] ruta) {
        this.ruta = ruta;
    }
    public Set getActorPeliculas() {
        return this.actorPeliculas;
    }
    
    public void setActorPeliculas(Set actorPeliculas) {
        this.actorPeliculas = actorPeliculas;
    }
    public Set getDirectorPeliculas() {
        return this.directorPeliculas;
    }
    
    public void setDirectorPeliculas(Set directorPeliculas) {
        this.directorPeliculas = directorPeliculas;
    }
    public Set getDetalles() {
        return this.detalles;
    }
    
    public void setDetalles(Set detalles) {
        this.detalles = detalles;
    }
    public Set getProductorPeliculas() {
        return this.productorPeliculas;
    }
    
    public void setProductorPeliculas(Set productorPeliculas) {
        this.productorPeliculas = productorPeliculas;
    }
    public Set getPeliculaIdiomas() {
        return this.peliculaIdiomas;
    }
    
    public void setPeliculaIdiomas(Set peliculaIdiomas) {
        this.peliculaIdiomas = peliculaIdiomas;
    }




}


