package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productor generated by hbm2java
 */
public class Productor  implements java.io.Serializable {


     private int idProductor;
     private String nombre;
     private Date fechaNacimiento;
     private Set productorPeliculas = new HashSet(0);

    public Productor() {
    }

	
    public Productor(int idProductor, String nombre, Date fechaNacimiento) {
        this.idProductor = idProductor;
        this.nombre = nombre;
        this.fechaNacimiento = fechaNacimiento;
    }
    public Productor(int idProductor, String nombre, Date fechaNacimiento, Set productorPeliculas) {
       this.idProductor = idProductor;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.productorPeliculas = productorPeliculas;
    }
   
    public int getIdProductor() {
        return this.idProductor;
    }
    
    public void setIdProductor(int idProductor) {
        this.idProductor = idProductor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getProductorPeliculas() {
        return this.productorPeliculas;
    }
    
    public void setProductorPeliculas(Set productorPeliculas) {
        this.productorPeliculas = productorPeliculas;
    }




}


