package cl.model.pojos;
// Generated 19/09/2018 03:38:10 PM by Hibernate Tools 4.3.1



/**
 * ProductorPelicula generated by hbm2java
 */
public class ProductorPelicula  implements java.io.Serializable {


     private Integer idproductorPelicula;
     private Pelicula pelicula;
     private Productor productor;

    public ProductorPelicula() {
    }

    public ProductorPelicula(Pelicula pelicula, Productor productor) {
       this.pelicula = pelicula;
       this.productor = productor;
    }
   
    public Integer getIdproductorPelicula() {
        return this.idproductorPelicula;
    }
    
    public void setIdproductorPelicula(Integer idproductorPelicula) {
        this.idproductorPelicula = idproductorPelicula;
    }
    public Pelicula getPelicula() {
        return this.pelicula;
    }
    
    public void setPelicula(Pelicula pelicula) {
        this.pelicula = pelicula;
    }
    public Productor getProductor() {
        return this.productor;
    }
    
    public void setProductor(Productor productor) {
        this.productor = productor;
    }




}


